name: Tests
on:
  pull_request: null
  push:
    branches:
      - main
      - devel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev,test]"
      - name: Run tests
        run: sh tests/run_tests_with_coverage.sh
      - name: Run mypy
        run: mypy || true
      - name: Run flake8
        run: flake8 || true
